name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test answer
      run: "pytest test-lambda.py"
    - name: Test answer 2
      run: "pytest test-lambda2.py"
    - name: deploy
      run:  |
        zip -j deploy.zip ./lambda_function.py
        aws lambda update-function-code --function-name=lambda-github --zip-file=fileb://deploy.zip

